In [ ]:
#Import library
import pandas as pd
import numpy as np

#Membuat Series

nilai = pd.Series([90,85,75,100])
print(nilai)

nilai = pd.Series(['Ana','Kiko','Ryan','Ben'])
print(nilai)

0     90
1     85
2     75
3    100
dtype: int64
0     Ana
1    Kiko
2    Ryan
3     Ben
dtype: object

In [ ]:
#Membuat DataFrame
data = {'Nama':['Andi','Budi','Citra'],'Umur':[20,21,22],'Kota':['Medan','Jakarta','Bandung']}
df = pd.DataFrame(data)
print(df)

    Nama  Umur     Kota
0   Andi    20    Medan
1   Budi    21  Jakarta
2  Citra    22  Bandung

In [ ]:
#Membaca Dataset
df = pd.read_csv('Data Penjualan Toko Buku.csv')
print(df)
df.head()
df.tail()
df.info()
df.describe()

df['jenis_item']
df[['jenis_item','jumlah']]
df.iloc[0]
df.iloc[0:7]
df.loc[0]

df.drop('jenis_item',axis=1)
df.rename(columns={'jumlah':'quantity'})

      id_transaksi       jenis_item  jumlah tanggal pembelian nama_customer  \
0         133889.0       Alat Tulis       1          1/1/2010  Stacy Campos
1         133889.0     Buku Sejarah       1          1/1/2010  Stacy Campos
2         133889.0   Buku Anak-Anak       2          1/1/2010  Stacy Campos
3         133889.0  Majalah Fashion       1          1/1/2010  Stacy Campos
4         133889.0   Majalah Berita       2          1/1/2010  Stacy Campos
...            ...              ...     ...               ...           ...
3235           NaN              NaN       2         4/30/2024           NaN
3236           NaN              NaN       6         4/30/2024           NaN
3237           NaN              NaN       1         4/30/2024           NaN
3238           NaN              NaN       9         4/30/2024           NaN
3239           NaN              NaN       1         4/30/2024           NaN

          total
0      120000.0
1      150000.0
2      400000.0
3      130000.0
4      600000.0
...         ...
3235   240000.0
3236  1800000.0
3237    90000.0
3238   180000.0
3239   100000.0

[3240 rows x 6 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3240 entries, 0 to 3239
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_transaksi       2469 non-null   float64
 1   jenis_item         2469 non-null   object
 2   jumlah             3240 non-null   int64
 3   tanggal pembelian  3237 non-null   object
 4   nama_customer      2469 non-null   object
 5   total              3238 non-null   float64
dtypes: float64(2), int64(1), object(3)
memory usage: 152.0+ KB

,id_transaksi,jenis_item,quantity,tanggal pembelian,nama_customer,total
0,133889.0,Alat Tulis,1,1/1/2010,Stacy Campos,120000.0
1,133889.0,Buku Sejarah,1,1/1/2010,Stacy Campos,150000.0
2,133889.0,Buku Anak-Anak,2,1/1/2010,Stacy Campos,400000.0
3,133889.0,Majalah Fashion,1,1/1/2010,Stacy Campos,130000.0
4,133889.0,Majalah Berita,2,1/1/2010,Stacy Campos,600000.0
...,...,...,...,...,...,...
3235,NaN,NaN,2,4/30/2024,NaN,240000.0
3236,NaN,NaN,6,4/30/2024,NaN,1800000.0
3237,NaN,NaN,1,4/30/2024,NaN,90000.0
3238,NaN,NaN,9,4/30/2024,NaN,180000.0
3239,NaN,NaN,1,4/30/2024,NaN,100000.0

In [ ]:
df.duplicated()
df.drop_duplicates()

0       False
1       False
2       False
3       False
4       False
        ...
3235     True
3236     True
3237     True
3238     True
3239     True
Length: 3240, dtype: bool

In [ ]:
df.isnull()
df.isnull().sum()

id_transaksi         771
jenis_item           771
jumlah                 0
tanggal pembelian      3
nama_customer        771
total                  2
dtype: int64

In [ ]:
df['id_transaksi']=df['id_transaksi']
df.dropna()

,id_transaksi,jenis_item,jumlah,tanggal pembelian,nama_customer,total
0,133889.0,Alat Tulis,1,1/1/2010,Stacy Campos,120000.0
1,133889.0,Buku Sejarah,1,1/1/2010,Stacy Campos,150000.0
2,133889.0,Buku Anak-Anak,2,1/1/2010,Stacy Campos,400000.0
3,133889.0,Majalah Fashion,1,1/1/2010,Stacy Campos,130000.0
4,133889.0,Majalah Berita,2,1/1/2010,Stacy Campos,600000.0
...,...,...,...,...,...,...
2464,134294.0,Alat Tulis,3,4/30/2024,Richard Jones,180000.0
2465,134294.0,Buku Sejarah,4,4/30/2024,Richard Jones,2400000.0
2466,134294.0,Buku Anak-Anak,2,4/30/2024,Richard Jones,80000.0
2467,134294.0,Majalah Fashion,9,4/30/2024,Richard Jones,1620000.0
2468,134294.0,Majalah Berita,4,4/30/2024,Richard Jones,320000.0